#!/bin/sh

# List of files to symlink
declare -a files=(
  ".local",
  ".tmuxinator",
  ".vim",
  ".vscode",
  ".zsh_custom",
  ".aliases",
  ".eslintrc.json",
  ".exports",
  ".functions",
  ".gitconfig",
  ".gitignore_global",
  ".gruvbox.dircolors",
  ".htoprc",
  ".inputrc",
  ".irbrc",
  ".macos",
  ".pryrc",
  ".tmux-osx.conf",
  ".tmux.conf",
  ".vimrc",
  ".vimrc_background",
  ".vimrc.bundles",
  ".yamllint",
  ".zsh_path",
  ".zshrc",
  "Brewfile",
)

echo "Installing..."

#!/bin/zsh
echo "Checking Command Line Tools for Xcode"
# Only run if the tools are not installed yet
# To check that try to print the SDK path
xcode-select -p &> /dev/null
if [ $? -ne 0 ]; then
  echo "Command Line Tools for Xcode not found. Installing from softwareupdate…"
# This temporary file prompts the 'softwareupdate' utility to list the Command Line Tools
  touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress;
  PROD=$(softwareupdate -l | grep "\*.*Command Line" | tail -n 1 | sed 's/^[^C]* //')
  softwareupdate -i "$PROD" --verbose;
else
  echo "Command Line Tools for Xcode have been installed."
fi

# Check for Homebrew and install if we don't have it
if test ! $(which brew); then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# Link files
link() {
  echo "Linking $1"
  rm -rf $HOME/$1
  ln -s $PWD/$1 $HOME/$1
}

# Removes .zshrc from $HOME (if it exists) and symlinks the .zshrc file from the .dotfiles
rm -rf $HOME/.zshrc
ln -s .zshrc $HOME/.zshrc

# Update Homebrew recipes
brew update

# Install all our dependencies with bundle (See Brewfile)
brew tap homebrew/bundle
brew bundle --file ./Brewfile

# Set default MySQL root password and auth type
mysql -u root -e "ALTER USER root@localhost IDENTIFIED WITH mysql_native_password BY 'password'; FLUSH PRIVILEGES;"

# Create a projects directories
mkdir -p $HOME/Code/github.com/voodoogq

# Clone Github repositories
chmod a+x ./clone
./clone

# Set macOS preferences - we will run this last because this will reload the shell
source ./.macos

for i in "${files[@]}"
do; link $i; done

