#!/bin/bash

COLOR=$1

if [ -n "$COLOR" ]; then

	# kills conky
	#
    pid=$(pgrep -f conkyrc.lua)

	if [ -n "$pid" ]; then
		ps -p $pid && kill $pid
	fi

	# Starts Conky
	#
    if [ -f $HOME/.conky/Conky-Skeleton/conkyrc.lua ]; then
        rm -f $HOME/.conky/Conky-Skeleton/conkyrc.lua
    fi

    ln -s $HOME/.conky/Conky-Skeleton/skeleton-$COLOR.lua $HOME/.conky/Conky-Skeleton/conkyrc.lua

	conky -c ~/.conky/Conky-Skeleton/conkyrc.lua &
else
	clear	
	echo ""	
	echo "Missing color argument (ie: skeleton_start blue)"
    echo ""
    echo "Available colours are:"
    echo "black, bluegrey, blue, brown, cyan, green, grey"
    echo "magenta, orange, red, teal, violet, yellow"
	echo ""
	exit 0
fi
