#!/bin/bash

COLOR1="black"
COLOR2="bluegrey"
COLOR3="blue"
COLOR4="brown"
COLOR5="cyan"
COLOR6="green"
COLOR7="grey"
COLOR8="magenta"
COLOR9="orange"
COLOR10="red"
COLOR11="teal"
COLOR12="violet"
COLOR13="yellow"

r=$(( $RANDOM % 13 + 1 ))

COLOR="COLOR$r"

# Starts Conky
#
if [ -f $HOME/.conky/Conky-Skeleton/conkyrc.lua ]; then
	rm -f $HOME/.conky/Conky-Skeleton/conkyrc.lua
fi

ln -s $HOME/.conky/Conky-Skeleton/skeleton-${!COLOR}.lua $HOME/.conky/Conky-Skeleton/conkyrc.lua
killall conky; conky -c "$HOME/.conky/Conky-Skeleton/conkyrc.lua" &
