#!/bin/bash

TIMER=$1

if [ -n "$TIMER" ]; then
	killall conky; conky -c "$HOME/.conky/Conky-Skeleton/skeleton-black.lua"; sleep $1
	killall conky; conky -c "$HOME/.conky/Conky-Skeleton/skeleton-bluegrey.lua"; sleep $1
	killall conky; conky -c "$HOME/.conky/Conky-Skeleton/skeleton-blue.lua"; sleep $1
	killall conky; conky -c "$HOME/.conky/Conky-Skeleton/skeleton-brown.lua"; sleep $1
	killall conky; conky -c "$HOME/.conky/Conky-Skeleton/skeleton-cyan.lua"; sleep $1
	killall conky; conky -c "$HOME/.conky/Conky-Skeleton/skeleton-green.lua"; sleep $1
	killall conky; conky -c "$HOME/.conky/Conky-Skeleton/skeleton-grey.lua"; sleep $1
	killall conky; conky -c "$HOME/.conky/Conky-Skeleton/skeleton-magenta.lua"; sleep $1
	killall conky; conky -c "$HOME/.conky/Conky-Skeleton/skeleton-orange.lua"; sleep $1
	killall conky; conky -c "$HOME/.conky/Conky-Skeleton/skeleton-red.lua"; sleep $1
	killall conky; conky -c "$HOME/.conky/Conky-Skeleton/skeleton-teal.lua"; sleep $1
	killall conky; conky -c "$HOME/.conky/Conky-Skeleton/skeleton-violet.lua"; sleep $1
	killall conky; conky -c "$HOME/.conky/Conky-Skeleton/skeleton-yellow.lua"; sleep $1
else
	clear	
	echo ""	
	echo "Missing number of seconds argument (ie: skeleton_demo 10)"
	echo ""
	exit 0
fi

killall conky
